mod_id=dtvinery
mod_name=Dynamic Trees for [Let's Do] Vinery
mod_license=MIT
mod_version=1.0.18
mod_group_id=com.skcraft.dtvinery
mod_authors=SKCraft
mod_description=Dynamic Trees compatibility for [Let's Do] Vinery.
mod_homepage=https://github.com/Magi1053/dynamictrees-addons/tree/main/mods/vinery
mod_issues=https://github.com/Magi1053/dynamictrees-addons/issues
modrinth_project_id=y8BUaAUa
