org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.230
loader_version_range=[1,)

mod_id=dtvinery
mod_name=Dynamic Trees for [Let's Do] Vinery
mod_license=MIT
mod_version=1.0.18
mod_group_id=com.skcraft.dtvinery
mod_authors=SKCraft
mod_description=Dynamic Trees compatibility for [Let's Do] Vinery.
mod_homepage=https://github.com/Magi1053/dynamictrees-addons/tree/main/mods/vinery
mod_issues=https://github.com/Magi1053/dynamictrees-addons/issues
modrinth_project_id=y8BUaAUa
