pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
    plugins {
        id 'net.neoforged.moddev' version '2.0.113'
        id 'com.modrinth.minotaur' version '2.9.0'
    }
}

rootProject.name = 'dynamictrees-addons'

['aether', 'vinery', 'meadow', 'rubber', 'spectrum', 'betterend'].each { name ->
    include name
    project(":$name").projectDir = file("mods/$name")
}
