mod_id=dtrubber
mod_name=Dynamic Trees Rubber
mod_license=MIT
mod_version=1.0.45
mod_group_id=com.skcraft.dtrubber
mod_authors=SKCraft
mod_description=A Dynamic Trees rubber species with latex tapping and early-game rubber items.
mod_homepage=https://github.com/Magi1053/dynamictrees-addons/tree/main/mods/rubber
mod_issues=https://github.com/Magi1053/dynamictrees-addons/issues
modrinth_project_id=cltZ2Lu1
