modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayURL="${mod_homepage}"
logoFile="assets/${mod_id}/logo.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dynamictrees"
type="required"
versionRange="[1.5.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aether"
type="required"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="deep_aether"
type="optional"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="emi"
type="optional"
versionRange="[1.0.0,)"
ordering="NONE"
side="CLIENT"
