mod_id=dtaether
mod_name=Dynamic Trees for The Aether
mod_license=MIT
mod_version=1.0.18
mod_group_id=com.skcraft.dtaether
mod_authors=SKCraft
mod_description=Dynamic Trees compatibility for The Aether, with optional Deep Aether trees.
mod_homepage=https://github.com/Magi1053/dynamictrees-addons/tree/main/mods/aether
mod_issues=https://github.com/Magi1053/dynamictrees-addons/issues
modrinth_project_id=G96mIrwD
