mod_id=dtbetterend
mod_name=Dynamic Trees for BetterEnd
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.skcraft.dtbetterend
mod_authors=SKCraft
mod_description=Dynamic Trees compatibility for BetterEnd, replacing End trees with growing species.
mod_homepage=https://github.com/Magi1053/dynamictrees-addons/tree/main/mods/betterend
mod_issues=https://github.com/Magi1053/dynamictrees-addons/issues
modrinth_project_id=
